import { Inter, Nunito } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const font = Nunito({ 
  subsets: ['latin'], 
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <body className={font.className}>
        <div className="pb-20 pt-28">
            {children}
        </div>
      </body>
    </html>
  )
}
