import { Nunito } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar/Navbar';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const font = Nunito({ 
  subsets: ['latin'], 
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <body className={font.className}>
        <Navbar/>
        <div className="bg-gray-300 pb-20 pt-28">
            {children}
        </div>
      </body>
    </html>
  )
}