export const FETCH_EVENT_REQUEST = 'FETCH_EVENT_REQUEST';
export const FETCH_EVENT_SUCCESS = 'FETCH_EVENT_SUCCESS';
export const FETCH_EVENT_FAILED = 'FETCH_EVENT_FAILED';

export const CLEAR_DETAIL = 'CLEAR_DETAIL';

export const SEARCH_EVENT = 'SEARCH_EVENT';