export const FETCH_EVENT_REQUEST = "FETCH_EVENT_REQUEST";
export const FETCH_EVENT_SUCCESS = "FETCH_EVENT_SUCCESS";
export const FETCH_EVENT_FAILED = "FETCH_EVENT_FAILED";

export const SEARCH_EVENT_REQUEST = "SEARCH_EVENT_REQUEST";
export const SEARCH_EVENT_SUCCESS = "SEARCH_EVENT_SUCCESS";
export const SEARCH_EVENT_FAILED = "SEARCH_EVENT_FAILED";

export const FILTER_EVENTTYPE = "FILTER_EVENTTYPE";
export const FILTER_EVENT_DATE = "FILTER_EVENT_DATE";

export const CREATE_EVENT = "CREATE_EVENT";
export const GET_EVENTS = "GET_EVENTS";

export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";